site_name: FiveM Loading Screen
site_url: https://fivem-loading.vercel.app/
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Getting Started: setup.md
  - Customization:
    - ğŸ¨ Overview: overview.md
    - ğŸ·ï¸ Watermark: watermark.md
    - ğŸ§· Social Headers: socials.md
    - ğŸ“œ Rules Panel: rules.md
    - ğŸ‘¥ Team Panel: team.md
    - ğŸ–¼ï¸ Gallery Grid: gallery.md
    - âŒ¨ï¸ Keyboard Overlay: keyboard-overlay.md
    - ğŸµ Music Player: music-player.md
  # - FAQ: faq.md
  - Upgrading: upgrade.md
  - Changelog: changelog.md
  - Future Plans: future-plans.md
extra_css:
  - stylesheets/custom-admonitions.css
